// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oaysadmsyrbpvbybfnis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9heXNhZG1zeXJicHZieWJmbmlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MjYyMjYsImV4cCI6MjA2MzQwMjIyNn0.YN8eiOnEkcIDfVmdWR58xBtzgyVk35YWaocI5hJ6UE8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);